"""Markdown generator for quality overview."""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Dict, List, Optional

from lucidshark.overview.models import (
    DomainStatus,
    IssuesBySeverity,
    Snapshot,
    TrendIndicator,
)

if TYPE_CHECKING:
    from lucidshark.core.models import ScanResult


@dataclass
class OverviewConfig:
    """Configuration for overview generation.

    Attributes:
        file: Output file path relative to project root.
        domains: Domains to include in overview.
        sections: Which sections to include.
        top_files: Number of top files to show (0 to disable).
    """

    file: str = "QUALITY.md"
    domains: List[str] = None  # type: ignore[assignment]
    top_files: int = 5

    # Section toggles
    health_score: bool = True
    domain_table: bool = True
    issue_breakdown: bool = True
    security_summary: bool = True
    coverage_breakdown: bool = True
    trend_chart: bool = True

    def __post_init__(self):
        if self.domains is None:
            self.domains = [
                "linting",
                "type_checking",
                "formatting",
                "testing",
                "sast",
                "sca",
                "iac",
                "container",
                "coverage",
                "duplication",
            ]


class OverviewGenerator:
    """Generates QUALITY.md from scan results and history.

    This class converts scan results into a human-readable markdown overview
    that can be committed to the repository.
    """

    def __init__(self, config: Optional[OverviewConfig] = None):
        """Initialize generator with configuration.

        Args:
            config: Overview configuration. Uses defaults if not provided.
        """
        self.config = config or OverviewConfig()

    def generate(
        self,
        snapshot: Snapshot,
        previous: Optional[Snapshot] = None,
        history: Optional[List[Snapshot]] = None,
        top_files: Optional[Dict[str, int]] = None,
    ) -> str:
        """Generate markdown overview content.

        Args:
            snapshot: Current quality snapshot.
            previous: Previous snapshot for trend comparison.
            history: Historical snapshots for trend chart.
            top_files: Map of file paths to issue counts.

        Returns:
            Markdown content as string.
        """
        lines: List[str] = []

        # Header
        lines.append("# Repository Quality Overview")
        lines.append("")
        lines.append(
            f"> **Branch:** {snapshot.branch} | "
            f"**Updated:** {self._format_date(snapshot.date)} | "
            f"**Commit:** `{snapshot.commit}`"
        )
        lines.append("")

        # Health Score
        if self.config.health_score:
            lines.extend(self._render_health_score(snapshot, previous))
            lines.append("")

        # Domain Table
        if self.config.domain_table and snapshot.domains:
            lines.extend(self._render_domain_table(snapshot, previous))
            lines.append("")

        # Issue Breakdown
        if self.config.issue_breakdown:
            lines.extend(self._render_issue_breakdown(snapshot, previous))
            lines.append("")

        # Top Files
        if self.config.top_files > 0 and top_files:
            lines.extend(self._render_top_files(top_files))
            lines.append("")

        # Security Summary
        if self.config.security_summary:
            security_domains = [
                d
                for d in snapshot.domains
                if d.domain in ("sast", "sca", "iac", "container")
            ]
            if security_domains:
                lines.extend(self._render_security_summary(security_domains))
                lines.append("")

        # Coverage Breakdown
        if self.config.coverage_breakdown and snapshot.coverage is not None:
            lines.extend(self._render_coverage(snapshot, previous))
            lines.append("")

        # Trend Chart
        if self.config.trend_chart and history and len(history) > 1:
            lines.extend(self._render_trend_chart(history))
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("<sub>Generated by [LucidShark](https://lucidshark.com)</sub>")

        return "\n".join(lines)

    def _format_date(self, iso_date: str) -> str:
        """Format ISO date to readable format."""
        # Extract date part (YYYY-MM-DD)
        if "T" in iso_date:
            date_part = iso_date.split("T")[0]
        else:
            date_part = iso_date[:10]
        return date_part

    def _render_health_score(
        self, snapshot: Snapshot, previous: Optional[Snapshot]
    ) -> List[str]:
        """Render health score section."""
        lines = []

        # Calculate trend
        prev_score = previous.score if previous else None
        trend = TrendIndicator.calculate(
            snapshot.score, prev_score, higher_is_better=True
        )

        # Score bar (10 segments)
        filled = int(snapshot.score)
        empty = 10 - filled
        bar = "█" * filled + "░" * empty

        # Format score line
        trend_str = f" {trend.arrow} {trend.delta_str}" if trend.delta_str else ""
        lines.append(f"## Health Score: {snapshot.score:.1f} / 10  {bar}{trend_str}")

        return lines

    def _render_domain_table(
        self, snapshot: Snapshot, previous: Optional[Snapshot]
    ) -> List[str]:
        """Render domain status table."""
        lines = []
        lines.append("| Domain | Status | Issues | Trend |")
        lines.append("|--------|--------|--------|-------|")

        # Build previous lookup
        prev_domains: Dict[str, DomainStatus] = {}
        if previous:
            prev_domains = {d.domain: d for d in previous.domains}

        for domain in snapshot.domains:
            # Filter by configured domains
            if domain.domain not in self.config.domains:
                continue

            status_icon = self._status_icon(domain.status)
            prev_domain = prev_domains.get(domain.domain)
            prev_count = prev_domain.issue_count if prev_domain else None

            trend = TrendIndicator.calculate(
                domain.issue_count, prev_count, higher_is_better=False
            )
            trend_str = f"{trend.arrow} {trend.delta_str}".strip()

            # Format domain name (handle acronyms)
            acronyms = {"sca", "sast", "iac"}
            if domain.domain in acronyms:
                domain_name = domain.domain.upper()
            else:
                domain_name = domain.domain.replace("_", " ").title()

            lines.append(
                f"| {domain_name} | {status_icon} {domain.status.title()} | "
                f"{domain.issue_count} | {trend_str} |"
            )

        return lines

    def _render_issue_breakdown(
        self, snapshot: Snapshot, previous: Optional[Snapshot]
    ) -> List[str]:
        """Render issue breakdown by severity."""
        lines = []
        lines.append("## Issues by Severity")
        lines.append("")

        severities = [
            ("critical", "🔴", snapshot.issues.critical),
            ("high", "🟠", snapshot.issues.high),
            ("medium", "🟡", snapshot.issues.medium),
            ("low", "🔵", snapshot.issues.low),
        ]

        for name, icon, count in severities:
            lines.append(f"- {icon} **{name.title()}:** {count}")

        return lines

    def _render_top_files(self, top_files: Dict[str, int]) -> List[str]:
        """Render top files by issue count."""
        lines = []
        lines.append("## Top Files by Issues")
        lines.append("")
        lines.append("| File | Issues |")
        lines.append("|------|--------|")

        # Sort by count descending, take top N
        sorted_files = sorted(top_files.items(), key=lambda x: x[1], reverse=True)
        for path, count in sorted_files[: self.config.top_files]:
            lines.append(f"| `{path}` | {count} |")

        return lines

    def _render_security_summary(
        self, security_domains: List[DomainStatus]
    ) -> List[str]:
        """Render security summary section."""
        lines = []
        lines.append("## Security Summary")
        lines.append("")
        lines.append("| Category | Issues | Status |")
        lines.append("|----------|--------|--------|")

        domain_labels = {
            "sast": "Vulnerabilities (SAST)",
            "sca": "Dependencies (SCA)",
            "iac": "Infrastructure (IaC)",
            "container": "Container",
        }

        for domain in security_domains:
            label = domain_labels.get(domain.domain, domain.domain.upper())
            status_icon = self._status_icon(domain.status)
            lines.append(f"| {label} | {domain.issue_count} | {status_icon} |")

        return lines

    def _render_coverage(
        self, snapshot: Snapshot, previous: Optional[Snapshot]
    ) -> List[str]:
        """Render coverage section."""
        lines = []
        lines.append("## Test Coverage")
        lines.append("")

        if snapshot.coverage is None:
            lines.append("*Coverage data not available*")
            return lines

        prev_cov = previous.coverage if previous else None
        trend = TrendIndicator.calculate(
            snapshot.coverage, prev_cov, higher_is_better=True
        )

        # Coverage bar
        filled = int(snapshot.coverage / 10)
        empty = 10 - filled
        bar = "█" * filled + "░" * empty

        trend_str = f" {trend.arrow} {trend.delta_str}%" if trend.delta_str else ""
        lines.append(f"**{snapshot.coverage:.1f}%** {bar}{trend_str}")

        return lines

    def _render_trend_chart(self, history: List[Snapshot]) -> List[str]:
        """Render ASCII trend chart."""
        lines = []
        lines.append("## Score Trend")
        lines.append("")

        # Take last 5 snapshots for compact display
        recent = history[:5]
        recent.reverse()  # Oldest first for chart

        if len(recent) < 2:
            return lines

        # Format: Score: 7.1 → 7.8 → 8.0 → 8.4
        scores = [f"{s.score:.1f}" for s in recent]
        score_line = "Score: " + " → ".join(scores)
        lines.append("```")
        lines.append(score_line)

        # Date labels
        dates = [self._format_date(s.date) for s in recent]
        # Align dates under scores (rough approximation)
        date_line = "       " + "   ".join(d[5:] for d in dates)  # MM-DD format
        lines.append(date_line)
        lines.append("```")

        return lines

    def _status_icon(self, status: str) -> str:
        """Get icon for status."""
        icons = {
            "pass": "✓",
            "warn": "⚠",
            "fail": "✗",
            "skipped": "○",
        }
        return icons.get(status.lower(), "○")


def calculate_score(
    issues: IssuesBySeverity,
    coverage: Optional[float] = None,
    duplication: Optional[float] = None,
) -> float:
    """Calculate overall quality score from metrics.

    The score is calculated as follows:
    - Start with 10.0
    - Deduct points for issues:
      - Critical: -2.0 each (max -4.0)
      - High: -1.0 each (max -3.0)
      - Medium: -0.3 each (max -2.0)
      - Low: -0.1 each (max -1.0)
    - Bonus/penalty for coverage:
      - Above 80%: up to +0.5
      - Below 60%: up to -1.0
    - Penalty for duplication:
      - Above 10%: up to -1.0

    Args:
        issues: Issue counts by severity.
        coverage: Test coverage percentage (0-100).
        duplication: Code duplication percentage (0-100).

    Returns:
        Quality score between 0.0 and 10.0.
    """
    score = 10.0

    # Issue penalties (with caps)
    score -= min(issues.critical * 2.0, 4.0)
    score -= min(issues.high * 1.0, 3.0)
    score -= min(issues.medium * 0.3, 2.0)
    score -= min(issues.low * 0.1, 1.0)

    # Coverage adjustment
    if coverage is not None:
        if coverage >= 80:
            # Bonus for good coverage
            score += min((coverage - 80) / 40, 0.5)  # Max +0.5 at 100%
        elif coverage < 60:
            # Penalty for poor coverage
            score -= min((60 - coverage) / 60, 1.0)  # Max -1.0 at 0%

    # Duplication penalty
    if duplication is not None and duplication > 10:
        score -= min((duplication - 10) / 20, 1.0)  # Max -1.0 at 30%

    return max(0.0, min(10.0, score))


def create_snapshot_from_scan(
    scan_result: "ScanResult",
    commit: str,
    branch: str,
    enabled_domains: Optional[List[str]] = None,
) -> Snapshot:
    """Create a snapshot from scan results.

    Args:
        scan_result: Results from lucidshark scan.
        commit: Git commit SHA.
        branch: Git branch name.
        enabled_domains: Domains that were scanned.

    Returns:
        Snapshot representing the scan results.
    """
    # Count issues by severity
    issues = IssuesBySeverity()
    for issue in scan_result.issues:
        if issue.ignored:
            continue
        severity = issue.severity.value.lower()
        if severity == "critical":
            issues.critical += 1
        elif severity == "high":
            issues.high += 1
        elif severity == "medium":
            issues.medium += 1
        elif severity == "low":
            issues.low += 1
        elif severity == "info":
            issues.info += 1

    # Get coverage
    coverage = None
    if scan_result.coverage_summary:
        coverage = scan_result.coverage_summary.coverage_percentage

    # Get duplication
    duplication = None
    if scan_result.duplication_summary:
        duplication = scan_result.duplication_summary.duplication_percent

    # Calculate score
    score = calculate_score(issues, coverage, duplication)

    # Build domain statuses from executed domains
    domains: List[DomainStatus] = []

    # Get issue counts by domain
    issue_counts: Dict[str, int] = {}
    if scan_result.summary and scan_result.summary.by_scanner:
        issue_counts = scan_result.summary.by_scanner.copy()

    # Get executed domains from metadata, or fall back to enabled_domains param
    executed = enabled_domains or []
    if scan_result.metadata and hasattr(scan_result.metadata, "executed_domains"):
        executed = scan_result.metadata.executed_domains or executed

    # Special handling for coverage and duplication (they have percentage metrics)
    special_domains = {"coverage", "duplication"}

    for domain_name in executed:
        if domain_name in special_domains:
            continue  # Handle separately below

        count = issue_counts.get(domain_name, 0)
        status = "pass" if count == 0 else "warn"
        domains.append(
            DomainStatus(
                domain=domain_name,
                status=status,
                issue_count=count,
            )
        )

    # Add coverage as a domain if executed
    if coverage is not None or "coverage" in executed:
        if coverage is not None:
            cov_status = (
                "pass" if coverage >= 80 else "warn" if coverage >= 60 else "fail"
            )
            domains.append(
                DomainStatus(
                    domain="coverage",
                    status=cov_status,
                    issue_count=0,
                    details={"percentage": coverage},
                )
            )
        else:
            domains.append(
                DomainStatus(
                    domain="coverage",
                    status="skipped",
                    issue_count=0,
                )
            )

    # Add duplication as a domain if executed
    if duplication is not None or "duplication" in executed:
        dup_issue_count = issue_counts.get("duplication", 0)
        if duplication is not None:
            dup_status = (
                "pass" if duplication <= 5 else "warn" if duplication <= 10 else "fail"
            )
            domains.append(
                DomainStatus(
                    domain="duplication",
                    status=dup_status,
                    issue_count=dup_issue_count,
                    details={"percentage": duplication},
                )
            )
        else:
            domains.append(
                DomainStatus(
                    domain="duplication",
                    status="skipped",
                    issue_count=0,
                )
            )

    return Snapshot.create_now(
        commit=commit,
        branch=branch,
        score=score,
        issues=issues,
        coverage=coverage,
        duplication=duplication,
        domains=domains,
    )


def get_top_files(
    scan_result: "ScanResult",
    limit: int = 5,
    project_root: Optional[str] = None,
) -> Dict[str, int]:
    """Get files with most issues.

    Args:
        scan_result: Scan results.
        limit: Maximum number of files to return.
        project_root: Project root for converting to relative paths.

    Returns:
        Dictionary mapping file paths to issue counts.
    """
    from pathlib import Path

    file_counts: Dict[str, int] = {}
    root = Path(project_root) if project_root else None

    for issue in scan_result.issues:
        if issue.ignored or issue.file_path is None:
            continue
        path = issue.file_path
        # Convert to relative path if project_root provided
        if root and path.is_absolute():
            try:
                path = path.relative_to(root)
            except ValueError:
                pass  # Path not under project root, keep absolute
        path_str = str(path)
        file_counts[path_str] = file_counts.get(path_str, 0) + 1

    # Sort and limit
    sorted_files = sorted(file_counts.items(), key=lambda x: x[1], reverse=True)
    return dict(sorted_files[:limit])
